/**
 * OnChainCoordination.tsx
 *
 * This component details the technical workings of Lit Protocol.
 */

import React from "react";
import GreyBoarderWhiteBgContainer from "../../../components/layout/GreyboardWhiteBgContainer";

const OnChainCoordination: React.FC = () => {
  const pageStyles = {
    container: {
      maxWidth: "1000px",
      margin: "0 auto",
      padding: "20px",
    },
    h1: {
      fontSize: "2.5rem",
      fontWeight: "700",
      color: "#1f2937",
      marginBottom: "24px",
    },
    h2: {
      fontSize: "2rem",
      fontWeight: "600",
      color: "#1f2937",
      marginBottom: "16px",
      borderBottom: "1px solid #e5e7eb",
      paddingBottom: "8px",
    },
    h3: {
      fontSize: "1.5rem",
      fontWeight: "600",
      color: "#374151",
      marginTop: "24px",
      marginBottom: "12px",
    },
    p: {
      fontSize: "1rem",
      lineHeight: "1.6",
      color: "#4b5563",
      marginBottom: "16px",
    },
    ol: {
      listStyleType: "decimal",
      paddingLeft: "20px",
      marginBottom: "16px",
    },
    li: {
      marginBottom: "8px",
      color: "#4b5563",
    },
  };

  return (
    <div style={pageStyles.container}>
      <h1 style={pageStyles.h1}>On-Chain Coordination Mechanisms</h1>

      <GreyBoarderWhiteBgContainer style={{ marginTop: "32px" }}>
        <p style={pageStyles.p}>
          While Lit Protocol itself is not a blockchain, it relies on on-chain
          coordination mechanisms to manage shared state and enforce
          cryptoeconomic security for each Lit node. This is achieved through
          Chronicle, an Arbitrum Orbit chain that functions as the protocol's
          on-chain registry and node coordination layer.
        </p>
        <p style={pageStyles.p}>
          Chronicle serves several important functions, namely:
        </p>
        <ol style={pageStyles.ol}>
          <li style={pageStyles.li}>
            <strong>Registering Keys and Associated Permissions:</strong> Each
            Programmable Key Pair (PKP) generated by the Lit node network is
            minted as an ERC-721 token on Chronicle. The permissions associated
            with these keys are managed via the related smart contracts
            on-chain.
          </li>
          <li style={pageStyles.li}>
            <strong>Node Staking and Rewards:</strong> Lit nodes must stake{" "}
            <code>$LITKEY</code> tokens on-chain in order to participate in
            network operations. Staking and rewards distribution take place on
            Chronicle.
          </li>
          <li style={pageStyles.li}>
            <strong>Service Payments:</strong> Developers who integrate the
            services provided by the Lit network into their own apps pay for the
            service via the payment contract deployed on Chronicle.
          </li>
        </ol>
        <p style={pageStyles.p}>
          All Lit node operators also run a replica node for the Orbit chain,
          ensuring Lit's on and off-chain operations remain tightly
          synchronized.
        </p>
      </GreyBoarderWhiteBgContainer>
    </div>
  );
};

export default OnChainCoordination;
